# =============================================================================
# SERVICES
# =============================================================================
services:
  # ---------------------------------------------------------------------------
  # DATABASE SERVICE
  # ---------------------------------------------------------------------------
  postgres:
    image: postgres:15
    container_name: smartrobe-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smartrobe-network

  # ---------------------------------------------------------------------------
  # ORCHESTRATOR SERVICE
  # ---------------------------------------------------------------------------
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    container_name: smartrobe-orchestrator
    environment:
      # Database Connection
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
      # Service URLs for new capability-based services
      HEURISTICS_SERVICE_URL: http://heuristics:8000
      LLM_MULTIMODAL_SERVICE_URL: http://llm-multimodal:8000
      FASHION_CLIP_SERVICE_URL: http://fashion-clip:8000
      
      # Image Processing Configuration
      MAX_IMAGE_SIZE_MB: ${MAX_IMAGE_SIZE_MB}
      ALLOWED_IMAGE_FORMATS: ${ALLOWED_IMAGE_FORMATS}
      IMAGE_DOWNLOAD_TIMEOUT: ${IMAGE_DOWNLOAD_TIMEOUT}
      
      # API Configuration
      SERVICE_REQUEST_TIMEOUT: ${SERVICE_REQUEST_TIMEOUT}
      MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS}
      
      # Storage & Environment
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${ORCHESTRATOR_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      heuristics:
        condition: service_healthy
      llm-multimodal:
        condition: service_healthy
      fashion-clip:
        condition: service_healthy
    networks:
      - smartrobe-network
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # CAPABILITY-BASED MODEL SERVICES
  # ---------------------------------------------------------------------------
  heuristics:
    build:
      context: .
      dockerfile: Dockerfile.heuristics
    container_name: smartrobe-heuristics
    environment:
      # Only what this service actually needs
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${HEURISTICS_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    networks:
      - smartrobe-network
    restart: unless-stopped

  llm-multimodal:
    build:
      context: .
      dockerfile: Dockerfile.llm_multimodal
    container_name: smartrobe-llm-multimodal
    environment:
      # Only what this service actually needs
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${LLM_MULTIMODAL_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    networks:
      - smartrobe-network
    restart: unless-stopped

  fashion-clip:
    build:
      context: .
      dockerfile: Dockerfile.fashion_clip
    container_name: smartrobe-fashion-clip
    environment:
      # Only what this service actually needs
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${FASHION_CLIP_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    networks:
      - smartrobe-network
    restart: unless-stopped

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  postgres_data:
    driver: local
  shared_storage:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  smartrobe-network:
    driver: bridge
