# =============================================================================
# SERVICES
# =============================================================================
services:
  # ---------------------------------------------------------------------------
  # DATABASE SERVICE
  # ---------------------------------------------------------------------------
  postgres:
    image: postgres:15
    container_name: smartrobe-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./shared/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smartrobe-network

  # ---------------------------------------------------------------------------
  # ORCHESTRATOR SERVICE
  # ---------------------------------------------------------------------------
  orchestrator:
    build:
      context: .
      dockerfile: ./services/orchestrator/Dockerfile
    container_name: smartrobe-orchestrator
    environment:
      # Database Connection
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
      # Service URLs
      HEURISTICS_SERVICE_URL: http://heuristics:8000
      LLM_MULTIMODAL_SERVICE_URL: http://llm-multimodal:8000
      FASHION_CLIP_SERVICE_URL: http://fashion-clip:8000
      MICROSOFT_FLORENCE_SERVICE_URL: http://microsoft-florence:8000

      
      # Configuration
      MAX_IMAGE_SIZE_MB: ${MAX_IMAGE_SIZE_MB}
      ALLOWED_IMAGE_FORMATS: ${ALLOWED_IMAGE_FORMATS}
      IMAGE_DOWNLOAD_TIMEOUT: ${IMAGE_DOWNLOAD_TIMEOUT}
      SERVICE_REQUEST_TIMEOUT: ${SERVICE_REQUEST_TIMEOUT}
      MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS}
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG_RETAIN_IMAGES: ${DEBUG_RETAIN_IMAGES:-false}
    ports:
      - "${ORCHESTRATOR_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    depends_on:
      postgres:
        condition: service_healthy
      heuristics:
        condition: service_healthy
      llm-multimodal:
        condition: service_healthy
      fashion-clip:
        condition: service_healthy
      microsoft-florence:
        condition: service_healthy

    networks:
      - smartrobe-network
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # MICROSERVICES
  # ---------------------------------------------------------------------------
  heuristics:
    build:
      context: .
      dockerfile: ./services/heuristics/Dockerfile
    container_name: smartrobe-heuristics
    environment:
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
      MICROSOFT_FLORENCE_SERVICE_URL: http://microsoft-florence:8000
    ports:
      - "${HEURISTICS_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    depends_on:
      microsoft-florence:
        condition: service_healthy
    networks:
      - smartrobe-network
    restart: unless-stopped

  llm-multimodal:
    build:
      context: .
      dockerfile: ./services/llm-multimodal/Dockerfile
    container_name: smartrobe-llm-multimodal
    environment:
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${LLM_MULTIMODAL_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    networks:
      - smartrobe-network
    restart: unless-stopped

  fashion-clip:
    build:
      context: .
      dockerfile: ./services/fashion-clip/Dockerfile
    container_name: smartrobe-fashion-clip
    environment:
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${FASHION_CLIP_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    networks:
      - smartrobe-network
    restart: unless-stopped

  microsoft-florence:
    build:
      context: .
      dockerfile: ./services/microsoft-florence/Dockerfile
    container_name: smartrobe-microsoft-florence
    environment:
      SHARED_STORAGE_PATH: ${SHARED_STORAGE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${MICROSOFT_FLORENCE_EXTERNAL_PORT}:8000"
    volumes:
      - shared_storage:${SHARED_STORAGE_PATH}
    networks:
      - smartrobe-network
    restart: unless-stopped



# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres_data
  shared_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./local_storage

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  smartrobe-network:
    driver: bridge