[project]
name = "smartrobe-shared"
version = "0.1.0"
description = "Shared components for Smartrobe microservices"
requires-python = ">=3.13"
dependencies = [
    "pydantic",
    "loguru", 
    "fastapi",
    "httpx",
]


